# Generated by Django 5.2.11 on 2026-09-03 10:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Anpurna Properties", max_length=120),
                ),
                ("app_name", models.CharField(default="anpurna", max_length=80)),
            ],
            options={
                "verbose_name": "Application Info",
                "verbose_name_plural": "Application Info",
                "db_table": "anpurna_applicationinfo",
            },
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("provider", models.CharField(default="exotel", max_length=30)),
                (
                    "provider_call_sid",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "voice_conversation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("Inbound", "Inbound"), ("Outbound", "Outbound")],
                        default="Inbound",
                        max_length=10,
                    ),
                ),
                ("from_number", models.CharField(max_length=20)),
                ("to_number", models.CharField(blank=True, default="", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ringing", "Ringing"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("No Answer", "No Answer"),
                        ],
                        default="Ringing",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                ("recording_url", models.URLField(blank=True, default="")),
            ],
            options={
                "db_table": "calls_call",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("CRM", "CRM Agent")],
                        default="CRM",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("max_active_leads", models.PositiveIntegerField(default=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_agent",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="AISession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("START", "Start"),
                            ("GREETING", "Greeting"),
                            ("INTENT", "Intent (Buy/Sell/Rent)"),
                            ("PROPERTY_TYPE", "Property type"),
                            ("BUDGET", "Budget"),
                            ("LOCATION", "Location"),
                            ("TIMELINE", "Timeline"),
                            ("CONFIRMATION", "Confirmation"),
                            ("COMPLETE", "Complete"),
                            ("HUMAN_HANDOFF", "Human handoff"),
                        ],
                        default="START",
                        max_length=20,
                    ),
                ),
                ("clarify_attempts", models.PositiveSmallIntegerField(default=0)),
                ("extracted_fields", models.JSONField(blank=True, default=dict)),
                (
                    "ended_reason",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_session",
                        to="myapp.call",
                    ),
                ),
            ],
            options={
                "db_table": "ai_app_aisession",
            },
        ),
        migrations.CreateModel(
            name="CallEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "provider_event_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="myapp.call",
                    ),
                ),
            ],
            options={
                "db_table": "calls_callevent",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requirement",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "budget_text",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("location", models.CharField(blank=True, default="", max_length=150)),
                (
                    "interest_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("key_points", models.JSONField(blank=True, default=list)),
                (
                    "suggested_action",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                ("generated_by", models.CharField(default="llm", max_length=50)),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="myapp.call",
                    ),
                ),
            ],
            options={
                "db_table": "calls_callsummary",
            },
        ),
        migrations.CreateModel(
            name="CallTranscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("turns", models.JSONField(blank=True, default=list)),
                ("full_text", models.TextField(blank=True, default="")),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript",
                        to="myapp.call",
                    ),
                ),
            ],
            options={
                "db_table": "calls_calltranscript",
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("mobile", models.CharField(max_length=20, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("AI Call", "AI Call"),
                            ("Manual", "Manual"),
                            ("Website", "Website"),
                        ],
                        default="AI Call",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Contacted", "Contacted"),
                            ("Qualified", "Qualified"),
                            ("Needs Human Follow-up", "Needs Human Follow-up"),
                            ("Follow-up Scheduled", "Follow-up Scheduled"),
                            ("Converted", "Converted"),
                            ("Lost", "Lost"),
                        ],
                        default="New",
                        max_length=30,
                    ),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[("Buy", "Buy"), ("Sell", "Sell"), ("Rent", "Rent")],
                        max_length=10,
                    ),
                ),
                ("property_type", models.CharField(max_length=50)),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("location", models.CharField(max_length=150)),
                ("timeline", models.CharField(blank=True, default="", max_length=100)),
                (
                    "interest_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("next_follow_up_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="myapp.agent",
                    ),
                ),
            ],
            options={
                "db_table": "leads_lead",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Followup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "followup_type",
                    models.CharField(
                        choices=[
                            ("Call", "Call"),
                            ("WhatsApp", "WhatsApp"),
                            ("Email", "Email"),
                            ("Site Visit", "Site Visit"),
                        ],
                        default="Call",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Missed", "Missed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("due_at", models.DateTimeField()),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="followups",
                        to="myapp.agent",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="myapp.lead",
                    ),
                ),
            ],
            options={
                "db_table": "followups_followup",
                "ordering": ["due_at"],
            },
        ),
        migrations.AddField(
            model_name="call",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calls",
                to="myapp.lead",
            ),
        ),
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status change"),
                            ("assignment", "Assignment"),
                            ("call_logged", "Call logged"),
                            ("note", "Note"),
                            ("whatsapp_sent", "WhatsApp sent"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="myapp.lead",
                    ),
                ),
            ],
            options={
                "db_table": "leads_leadactivity",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("to_number", models.CharField(max_length=20)),
                ("template_name", models.CharField(max_length=100)),
                ("body", models.TextField()),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Queued", "Queued"),
                            ("Sent", "Sent"),
                            ("Delivered", "Delivered"),
                            ("Read", "Read"),
                            ("Failed", "Failed"),
                        ],
                        default="Queued",
                        max_length=20,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages",
                        to="myapp.call",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_messages",
                        to="myapp.lead",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_whatsappmessage",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_label", models.CharField(default="system", max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("object_type", models.CharField(max_length=64)),
                ("object_id", models.CharField(blank=True, default="", max_length=64)),
                ("method", models.CharField(blank=True, default="", max_length=8)),
                ("path", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_auditlog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_audit_object__1f9df3_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_audit_created_2c1626_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status"], name="leads_lead_status_e23abe_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["mobile"], name="leads_lead_mobile_0244d4_idx"),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["status", "due_at"], name="followups_f_status_874c0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["status"], name="calls_call_status_03473e_idx"),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["from_number"], name="calls_call_from_nu_4c17b4_idx"
            ),
        ),
    ]
