# Generated by Django 5.2.11 on 2026-09-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_user_managers_passwordresetotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("incoming_call", "Incoming Call"),
                    ("status_update", "Status Update"),
                    ("ai_conversed", "AI Conversed"),
                ],
                default="incoming_call",
                max_length=50,
            ),
        ),
    ]
