# Generated by Django 5.2.11 on 2026-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_callevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("AI Call", "AI Call"),
                    ("Manual", "Manual"),
                    ("Manual Entry", "Manual Entry"),
                    ("Website", "Website"),
                ],
                default="AI Call",
                max_length=30,
            ),
        ),
    ]
