# Generated by Django 5.2.11 on 2026-09-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_lead_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="last_assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("AI Call", "AI Call"),
                    ("Manual", "Manual"),
                    ("Website", "Website"),
                ],
                default="AI Call",
                max_length=20,
            ),
        ),
    ]
