# Generated by Django 5.2.11 on 2026-09-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_agent_last_assigned_at_alter_lead_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessage",
            name="parameters",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="template_language",
            field=models.CharField(default="hi", max_length=10),
        ),
    ]
